### ISSUE TITLE
Error in conda env creation because of metaworld version

### ISSUE THREAD

**Issue by SapanaChaudhary** [luckeciano/transformers-metarl#5]
Hi Luckeciano, 

I get the following error during conda env creation, because of metaworld version. 

```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement metaworld==0.0.0 (from -r /home/---/transformers-metarl/condaenv.w9ef9n2x.requirements.txt (line 27)) (from versions: 0.0.1.dev0)
ERROR: No matching distribution found for metaworld==0.0.0 (from -r /home/---/transformers-metarl/condaenv.w9ef9n2x.requirements.txt (line 27))

failed

CondaEnvException: Pip failed
```

Which of the following metaworlds is environment.yml trying to install? 
1. https://pypi.org/project/metaworld/
2. https://github.com/Farama-Foundation/Metaworld

I understand the paper includes experiments on 2. 
Could you please share how to fix the error and use your repo to run experiments on meta-world tasks? 

Thank you, 
Sapana

**Comment by hjh0119** [comment]
Have you resolved it? I installed the GitHub version, but it encountered an error.

./transformer_ppo_ml1.py --wm_embedding_hidden_size=32 --n_heads=4 --d_model=32 --layers=4 --wm_size=5 --em_size=5 --dim_ff=128 --meta_batch_size=25 --episode_per_task=10 --discount=0.9 --gae_lambda=0.95 --lr_clip_range=0.2 --policy_lr=5e-05 --vf_lr=5e-05 --minibatch_size=32 --max_opt_epochs=10 --policy_ent_coeff=0.0 --entropy_method=regularized --architecture=Encoder --policy_head_input=latest_memory --init_std=1.0 --remove_ln --tfixup --learn_std --pre_lnorm --init_params --use_softplus_entropy --policy_lr_schedule=no_schedule --vf_lr_schedule=no_schedule --decay_epoch_init=500 --decay_epoch_end=3500 --min_lr_factor=0.0001 --policy_head_type=Default --output_weights_scale=0.01 --env_name=ML10 --max_episode_length=500
/home/hjh/transformers-metarl/src/garage/experiment/experiment.py:551: UserWarning: Archiving a launch repo larger than 8MiB. This may be slow. Set archive_launch_repo=False in wrap_experiment to disable this behavior.
  warnings.warn('Archiving a launch repo larger than 8MiB. This may be '
2023-07-17 10:24:06 | [rl2_transformer_ml1] Logging to /home/hjh/transformers-metarl/examples/torch/data/local/experiment/rl2_transformer_ml1_4
/home/hjh/transformers-metarl/src/garage/experiment/deterministic.py:36: UserWarning: Enabeling deterministic mode in PyTorch can have a performance impact when using GPU.
  warnings.warn(
Traceback (most recent call last):
  File "./transformer_ppo_ml1.py", line 224, in <module>
    rl2_transformer_ml1()
  File "/home/lab304/miniconda3/envs/metarl/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/lab304/miniconda3/envs/metarl/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/lab304/miniconda3/envs/metarl/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lab304/miniconda3/envs/metarl/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/hjh/transformers-metarl/src/garage/experiment/experiment.py", line 369, in __call__
    result = self.function(ctxt, **kwargs)
  File "./transformer_ppo_ml1.py", line 119, in rl2_transformer_ml1
    env=MetaWorldSetTaskEnv(ml_env, 'test'),
  File "/home/hjh/transformers-metarl/src/garage/envs/metaworld_set_task_env.py", line 63, in __init__
    self.set_task(self._tasks_by_env[self._env_list[0]][0])
  File "/home/hjh/transformers-metarl/src/garage/envs/metaworld_set_task_env.py", line 121, in set_task
    self._construct_env_if_needed()
  File "/home/hjh/transformers-metarl/src/garage/envs/metaworld_set_task_env.py", line 172, in _construct_env_if_needed
    env = envs.GymEnv(env, max_episode_length=env.max_path_length)
  File "/home/hjh/transformers-metarl/src/garage/envs/gym_env.py", line 140, in __init__
    raise ValueError('GymEnv can take env as either a string, '
ValueError: GymEnv can take env as either a string, or an Gym environment, but got type <class 'metaworld.envs.mujoco.sawyer_xyz.v2.sawyer_drawer_open_v2.SawyerDrawerOpenEnvV2'> instead.
Exception ignored in: <function Environment.__del__ at 0x7f30240831f0>
Traceback (most recent call last):
  File "/home/hjh/transformers-metarl/src/garage/_environment.py", line 355, in __del__
    self.close()
  File "/home/hjh/transformers-metarl/src/garage/envs/gym_env.py", line 301, in close
    self._env.close()
AttributeError: 'NoneType' object has no attribute 'close'
