### ISSUE TITLE
Garage mujoco import error 

### ISSUE THREAD

**Issue by SapanaChaudhary** [luckeciano/transformers-metarl#6]
Hi, 

On running the halfcheetah code, I get the following error:

```
Traceback (most recent call last):
  File "./transformer_ppo_halfcheetah.py", line 10, in <module>
    from garage.envs.mujoco.half_cheetah_vel_env import HalfCheetahVelEnv
  File "../anaconda3/envs/transformer-metarl/lib/python3.7/site-packages/garage/envs/mujoco/__init__.py", line 9, in <module>
    from garage.envs.mujoco.ant_dir import AntDirEnv
  File "../anaconda3/envs/transformer-metarl/lib/python3.7/site-packages/garage/envs/mujoco/ant_dir.py", line 5, in <module>
    from garage.envs.mujoco.ant import AntEnv
  File "../anaconda3/envs/transformer-metarl/lib/python3.7/site-packages/garage/envs/mujoco/ant.py", line 3, in <module>
    from .mujoco_env import MujocoEnv
  File "../anaconda3/envs/transformer-metarl/lib/python3.7/site-packages/garage/envs/mujoco/mujoco_env.py", line 8, in <module>
    from garage.envs.mujoco.core.serializable import Serializable
ModuleNotFoundError: No module named 'garage.envs.mujoco.core'
```

Could you please let me know if you have come across this and how you fixed it. Thanks!

**Comment by SapanaChaudhary** [comment]
Just a few followup questions:
1. Are you using garage from the local src/garage folder or the one from pip installation? Because pip installed package doesn't have garage/envs/mujoco/mujoco/core folder. 
2. As an alternative to using garage package, I did an appropriate sys.path.append in transfomer_ppo_halfcheetah.py to use the local src/garage. But, that gives the following error: 

```
File "./src/garage/experiment/experiment.py", line 369, in __call__
    result = self.function(ctxt, **kwargs)
  File "examples/torch/transformer_ppo_halfcheetah.py", line 148, in transformer_ppo_halfcheetah
    max_episode_length=max_episode_length)).spec
  File "./src/garage/envs/gym_env.py", line 147, in __init__
    self._render_modes = self._env.metadata['render.modes']
KeyError: 'render.modes'
```

I am trying to use the work as a baseline. It would be really nice if you could share your thoughts on how to setup the conda env appropriately, thanks!

**Comment by ZlSong417** [comment]
@SapanaChaudhary I solved same problem by downgrading gym to 0.21.0
```
pip uninstall gym
pip install gym==0.21.0
```
